# This is a basic workflow to help you get started with Actions

name: Releases

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/386, darwin/amd64
        goos: [linux, windows, freebsd]
        goarch: ["386", amd64, arm]
        include:
          - goos: darwin
            goarch: amd64
    steps:
    - uses: actions/checkout@v2

    - name: Set APP_VERSION env
      run: echo ::set-env name=APP_VERSION::$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )
    - name: Set BUILD_TIME env
      run: echo ::set-env name=BUILD_TIME::$(date)  
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0        

    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.15.linux-amd64.tar.gz"
        build_flags: -v
        ldflags: -X "github.com/ariejan/zelda/cmd.AppVersion=${{ env.APP_VERSION }}" -X "github.com/ariejan/zelda/cmd.BuildTime=${{ env.BUILD_TIME }}"    
        extra_files: LICENSE README.md zelda.example.yaml
